sendMessage: true
Messages:
 OpenedDoor: '&2%player% &fopened the door of day &2%day%'
 LikePresent: '&bUhhh :) Do you like the Present for the Day &2%day%&b?'
 CanOpen: '&2You can open the door &b%number%&2!'
 AlreadyGot: '&eYou already got the present for today. Come back tomorrow!'
 Only24Doors: '&aThe advent calendar just has 24 doors :) Sorry'
 
Day_1:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_2:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_3:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_4:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_5:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_6:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_7:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_8:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_9:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_10:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_11:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_12:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_13:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_14:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_15:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_16:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_17:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_18:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_19:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_20:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_21:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_22:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_23:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_24:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas