sendMessage: true
Message: '%player% opend a Door Day %day%'

Day_01:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_02:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_03:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_04:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_05:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_06:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_07:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_08:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_09:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_10:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_11:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_12:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_13:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_14:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_15:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_16:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_17:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_18:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_19:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_20:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_21:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_22:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_23:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas
Day_24:
  DoCommand: false
  GiveItems: true
  Items:
  - 35,10,10
  Command:
  - say Its Christmas